// TABLE AI website copy — verbatim from server/seed.ts (ksamint/table-ai-website). Every string is {zh, en}.
const B = (zh, en) => ({ zh, en });
const SITE = {
  nav: [
    { href: "/studio", label: B("工作室", "Studio") },
    { href: "/protocol", label: B("協議", "Protocol") },
    { href: "/network", label: B("網絡", "Network") },
    { href: "/business", label: B("AI實驗室", "AI Labs") },
    { href: "/about", label: B("關於", "About") },
  ],
  hero: {
    eyebrow: B("全球協同基礎設施", "Global Collaborative Infrastructure"),
    title: B("TABLE AI", "TABLE AI"),
    subtitle: B("跨越智能與實體經濟邊界的全球協同基礎設施", "Global Collaborative Infrastructure Bridging Intelligence and the Real Economy"),
    tagline: B("跨越信任與體驗的鴻溝", "Bridging the Trust and Experience Divide"),
    insight: B("在全球企業加速擁抱大模型技術的當下，TABLE AI 洞察到：AI 智能體向核心業務線滲透的最大瓶頸，已不再是算力或模型參數，而是「人與數據」的交匯摩擦。", "As global enterprises accelerate their adoption of large model technologies, TABLE AI has identified a critical insight: the greatest bottleneck for AI agents penetrating core business lines is no longer computing power or model parameters, but the friction at the intersection of people and data."),
    cta1: B("探索 AHA 架構", "Explore AHA Architecture"),
    cta2: B("了解更多", "Learn More"),
  },
  stats: [
    { value: 3, suffix: "", label: B("專家 AI 產品", "Expert-AI Products") },
    { value: 8, suffix: "+", label: B("侍天簽約餐飲品牌", "Tiansight Signed Restaurant Brands"), accent: true },
    { value: 7, suffix: "", label: B("天交付經營診斷報告", "Days to a Diagnostic Report") },
    { value: 7, suffix: "+", label: B("全球樞紐節點", "Global Hub Nodes") },
  ],
  insight: { eyebrow: B("核心洞察與企業使命", "Our Vision & Mission") },
  thresholds: [
    { label: B("臨界點 01", "Threshold 01"), title: B("信任臨界點", "Trust Threshold"), desc: B("缺乏零信任的數據流轉與財務清算機制，企業不敢開放核心場景，多方協作的利益分配無法達成共識。", "Without zero-trust data circulation and financial settlement mechanisms, enterprises dare not open core scenarios, and consensus on multi-party interest distribution remains elusive.") },
    { label: B("臨界點 02", "Threshold 02"), title: B("體驗臨界點", "Experience Threshold"), desc: B("在極高複雜度和零容錯率的商業博弈中，純粹的算法存在物理盲區，無法獨立交付具備專業深度與責任兜底的極致體驗。", "In high-complexity, zero-tolerance business dynamics, pure algorithms have physical blind spots and cannot independently deliver the ultimate experience with professional depth and accountability.") },
  ],
  aha: {
    eyebrow: B("底層協作架構：AHA 體系", "The AHA Architecture"),
    title: B("AHA 體系", "The AHA Architecture"),
    subtitle: B("Agent-Human-Assets 智能體-人-資產 混合協作底層架構", "Agent-Human-Assets Hybrid Collaboration Architecture"),
    content: B("為解決產業痛點，TABLE AI 自主研發了 AHA（Agent-Human-Assets，智能體-人-資產）混合協作底層架構。作為智能經濟的「協議層」，AHA 架構原生打通了機器算力、人類智力與物理資產的交互鏈路。它將複雜的現實商業系統轉化為可計算、可追溯、絕對可信的代碼逻輯，為 AI 在真實世界的大規模部署提供了不可或缺的技術基石。", "To solve industry pain points, TABLE AI has independently developed the AHA (Agent-Human-Assets) hybrid collaboration architecture. As the 'protocol layer' of the intelligent economy, the AHA architecture natively connects the interaction chains of machine computing power, human intelligence, and physical assets. It transforms complex real-world business systems into computable, traceable, and absolutely trustworthy code logic, providing an indispensable technological cornerstone for the large-scale deployment of AI in the real world."),
    items: [
      { letter: "A", label: B("Agent 智能體", "Agent"), desc: B("機器算力", "Machine Computing"), desc2: B("機器算力與自動化執行", "Machine computing power and automated execution"), detail: B("將複雜的現實商業系統轉化為可計算、可追溯的代碼逻輯", "Transforming complex real-world business systems into computable, traceable code logic") },
      { letter: "H", label: B("Human 人", "Human"), desc: B("人類智力", "Human Intelligence"), desc2: B("人類智力與專業背書", "Human intelligence and professional endorsement"), detail: B("保留人類不可替代的專業背書與極限糾偏能力", "Preserving irreplaceable human professional endorsement and ultimate error-correction capabilities") },
      { letter: "A", label: B("Assets 資產", "Assets"), desc: B("物理資產", "Physical Assets"), desc2: B("物理資產與實體經濟", "Physical assets and real economy"), detail: B("原生打通機器算力、人類智力與物理資產的交互鏈路", "Natively connecting the interaction chains of machine computing, human intelligence, and physical assets") },
    ],
    visualEyebrow: B("底層架構", "Foundation Architecture"),
    visualTitle: B("AHA 體系 —— 智能體-人-資產", "AHA Architecture — Agent-Human-Assets"),
  },
  business: {
    eyebrow: B("商業部署矩陣", "Business Deployment Matrix"),
    title: "1+1+X",
    subtitle: B("戰略飛輪", "Strategic Flywheel"),
    content: B("基於 AHA 底層架構，TABLE AI 構建了極具延展性的「1+1+X」商業落地矩陣。這不僅是一套技術部署方案，更是系統性破解行業痛點的結構化解法。", "Built upon the AHA architecture, TABLE AI has constructed a highly extensible '1+1+X' business deployment matrix. This is not merely a technology deployment plan, but a structured solution for systematically solving industry pain points."),
    learnMore: B("深入了解", "Learn More"),
  },
  protocol: {
    num: "01", pillar: B("跨越信任臨界點", "Crossing the Trust Threshold"),
    title: B("第一個「1」：跨越「信任」臨界點", "The First '1': Crossing the Trust Threshold"),
    subtitle: B("一套零信任、自迭代的合規清算系統", "A Zero-Trust, Self-Iterating Compliance Settlement System"),
    content: B("基於「零信任（Zero-Trust）」架構打造的企業級智能協同與全球分帳系統。它在確保數據「可用不可見」的前提下，精準量化多方協作貢獻，實現交易即秒級自動清算。系統內置自迭代機制，深度契合國家信通院可信算力標準及全球多邊稅務合規要求，用系統級的確定性徹底消除跨組織協作的摩擦成本。", "An enterprise-grade intelligent collaboration and global settlement system built on Zero-Trust architecture. While ensuring data remains 'usable but invisible,' it precisely quantifies multi-party collaboration contributions and achieves instant automatic settlement at the moment of transaction. With built-in self-iterating mechanisms, the system deeply aligns with CAICT trusted computing standards and global multilateral tax compliance requirements, using system-level certainty to completely eliminate the friction costs of cross-organizational collaboration."),
    overview: B("協議概述", "Protocol Overview"),
    mechanismsEyebrow: B("核心機制", "Core Mechanisms"), mechanismsTitle: B("零信任清算系統如何運轉", "How the Zero-Trust Settlement System Works"),
    features: [
      { title: B("零信任數據流轉", "Zero-Trust Data Circulation"), content: B("確保數據「可用不可見」，在保護商業機密的前提下實現多方協作的精準貢獻量化與利益分配。", "Ensures data remains 'usable but invisible,' enabling precise contribution quantification and interest distribution in multi-party collaboration while protecting commercial secrets.") },
      { title: B("秒級自動清算", "Instant Automatic Settlement"), content: B("交易達成的瞬間，系統觸發零摩擦、零爭議的秒級自動清算，徹底消除跨組織協作的結算延遲。", "The moment a transaction is completed, the system triggers zero-friction, zero-dispute instant automatic settlement, completely eliminating settlement delays in cross-organizational collaboration.") },
      { title: B("全球合規自迭代", "Global Compliance Self-Iteration"), content: B("系統內置自迭代機制，深度契合國家信通院可信算力標準及全球多邊稅務合規要求，確保絕對合規。", "Built-in self-iterating mechanisms deeply align with CAICT trusted computing standards and global multilateral tax compliance requirements, ensuring absolute compliance.") },
    ],
    highlightsEyebrow: B("技術亮點", "Technical Highlights"),
    highlights: [
      { title: B("零信任架構", "Zero-Trust Architecture"), desc: B("確保數據可用不可見，在保護商業機密的前提下實現多方協作的精準貢獻量化", "Ensures data remains usable but invisible, enabling precise contribution quantification in multi-party collaboration while protecting commercial secrets") },
      { title: B("秒級自動清算", "Instant Automatic Settlement"), desc: B("交易達成的瞬間觸發零摩擦、零爭議的秒級自動清算，徹底消除結算延遲", "Instant zero-friction, zero-dispute automatic settlement triggered at the moment of transaction, completely eliminating settlement delays") },
      { title: B("可信算力標準", "Trusted Computing Standards"), desc: B("深度契合國家信通院可信算力標準，確保計算過程透明可審計", "Deeply aligned with CAICT trusted computing standards, ensuring transparent and auditable computation processes") },
      { title: B("全球多邊合規", "Global Multilateral Compliance"), desc: B("系統內置自迭代機制，深度契合全球多邊稅務合規要求，用系統級確定性消除摩擦成本", "Built-in self-iterating mechanisms aligned with global multilateral tax compliance requirements, using system-level certainty to eliminate friction costs") },
    ],
    ctaTitle: B("探索 OPC Global 專業級協作網絡", "Explore the OPC Global Professional Network"), ctaLabel: B("了解網絡", "Discover the Network"),
  },
  network: {
    num: "02", pillar: B("跨越體驗臨界點", "Crossing the Experience Threshold"),
    title: B("第二個「1」：跨越「體驗」臨界點", "The Second '1': Crossing the Experience Threshold"),
    subtitle: B("OPC Global — 全球化專業級協作網絡", "OPC Global — A Global Professional Collaboration Network"),
    content: B("單純的代碼無法獨立應對真實商業的複雜性，高風險場景依然需要人在回路以明確權責、控制風險。依託遍布倫敦、巴塞爾、北美及大中華區核心樞紐的算力與人才節點，我們構建了基於「人在回路 (Human-in-the-loop)」理念的 OPC Global 超級專家網絡。我們將頂尖專家的隱性經驗轉化為 AI 模型，同時保留人類不可替代的專業背書與極限糾偏能力，為 AI 的真實商業交付提供最高標準的體驗兜底。", "Code alone cannot independently handle the complexity of real-world business. High-risk scenarios still require humans in the loop to clarify responsibilities and control risks. Leveraging computing power and talent nodes across core hubs in London, Basel, North America, and Greater China, we have built the OPC Global super expert network based on the 'Human-in-the-loop' philosophy. We transform the tacit experience of top experts into AI models while preserving the irreplaceable human professional endorsement and ultimate error-correction capabilities, providing the highest standard of experience assurance for AI's real-world business delivery."),
    overview: B("網絡概述", "Network Overview"),
    pillarsEyebrow: B("核心支柱", "Core Pillars"), pillarsTitle: B("OPC Global 網絡架構", "OPC Global Network Architecture"),
    features: [
      { title: B("人在回路 (Human-in-the-loop)", "Human-in-the-Loop"), content: B("高風險場景依然需要人在回路以明確權責、控制風險，保留人類不可替代的專業背書與極限糾偏能力。", "High-risk scenarios still require humans in the loop to clarify responsibilities and control risks, preserving the irreplaceable human professional endorsement and ultimate error-correction capabilities.") },
      { title: B("隱性經驗 AI 化", "Tacit Experience to AI"), content: B("將遍布頂尖高校、醫療機構及商業領域的專家隱性經驗轉化為可規模化的 AI 專家模型。", "Transforming tacit expert experience across top universities, medical institutions, and business domains into scalable AI expert models.") },
      { title: B("全球樞紐網絡", "Global Hub Network"), content: B("依託遍布倫敦、巴塞爾、北美及大中華區核心樞紐的算力與人才節點，構建全球化專業級協作網絡。", "Leveraging computing power and talent nodes across core hubs in London, Basel, North America, and Greater China to build a global professional collaboration network.") },
    ],
    hubsEyebrow: B("全球布局", "Global Presence"), hubsTitle: B("樞紐城市網絡", "Hub City Network"),
    hubs: [
      { city: B("中國香港", "Hong Kong"), region: B("大中華區", "Greater China") }, { city: B("倫敦", "London"), region: B("歐洲", "Europe") }, { city: B("巴塞爾", "Basel"), region: B("歐洲", "Europe") }, { city: B("北美", "North America"), region: B("美洲", "Americas") },
      { city: B("北京", "Beijing"), region: B("大中華區", "Greater China") }, { city: B("上海", "Shanghai"), region: B("大中華區", "Greater China") }, { city: B("深圳", "Shenzhen"), region: B("大中華區", "Greater China") }, { city: B("澳門", "Macau"), region: B("大中華區", "Greater China") },
    ],
    metrics: [
      { icon: "users", num: B("Human-in-the-Loop", "Human-in-the-Loop"), label: B("人在回路", "Human-in-the-Loop"), desc: B("高風險場景依然需要人在回路以明確權責、控制風險，保留人類不可替代的專業背書與極限糾偏能力", "High-risk scenarios still require humans in the loop to clarify responsibilities and control risks, preserving irreplaceable human professional endorsement and ultimate error-correction capabilities") },
      { icon: "cpu", num: B("AI + Expert", "AI + Expert"), label: B("隱性經驗 AI 化", "Tacit Experience to AI"), desc: B("將頂尖專家的隱性經驗轉化為 AI 模型，實現專業知識的規模化複制與持續進化", "Transforming tacit experience of top experts into AI models, enabling scalable replication and continuous evolution of professional knowledge") },
      { icon: "zap", num: B("最高標準", "Highest Standard"), label: B("體驗兜底", "Experience Assurance"), desc: B("為 AI 的真實商業交付提供最高標準的體驗兜底，確保專業深度與責任擔當", "Providing the highest standard of experience assurance for AI's real-world business delivery, ensuring professional depth and accountability") },
    ],
    ctaTitle: B("探索 AI 實驗室", "Explore AI Labs"), ctaLabel: B("了解實驗室", "Discover AI Labs"),
  },
  labs: {
    num: "03", pillar: B("引領範式轉移", "Leading Paradigm Shift"),
    title: B("乘數「X」：引領範式轉移", "The Multiplier 'X': Leading Paradigm Shift"),
    subtitle: B("X 個具備行業領先範例的 AI 轉型場景", "X Industry-Leading AI Transformation Scenarios"),
    content: B("TABLE AI 正將 1+1 的基礎設施能力，注入亟待 AI 轉型的高淨值、重資產場景，打造標桿級範例。", "TABLE AI is injecting its 1+1 infrastructure capabilities into high-value, heavy-asset scenarios urgently awaiting AI transformation, creating benchmark-level exemplars."),
    overview: B("實驗室概述", "Labs Overview"),
    homeEyebrow: B("乘數「X」", "Multiplier X"), homeTitle: B("X 個 AI 轉型場景", "X AI Transformation Scenarios"), viewAll: B("查看全部", "View All"), details: B("了解詳情", "Details"),
    items: [
      { num: "X1", title: B("合規商旅與供應鏈管家", "Compliant Business Travel & Supply Chain Steward"), subtitle: B("重塑大型政企內部協作信任", "Reshaping Internal Collaboration Trust in Large Government and Enterprise Organizations"), content: B("緊貼宏觀「降本增效」剛需，通過算法驅動，為大型國資與私企提供徹底透明、消除一切灰色地帶的差旅管家系統，重塑大型政企內部協作信任。", "Closely aligned with the macro demand for cost reduction and efficiency improvement, providing large state-owned and private enterprises with completely transparent business travel management systems through algorithm-driven solutions, eliminating all gray areas and reshaping internal collaboration trust."),
        details: [{ label: B("核心策略", "Core Strategy"), value: B("緊貼宏觀降本增效剛需，通過算法驅動，為大型國資與私企提供徹底透明、消除一切灰色地帶的差旅管家系統，重塑大型政企內部協作信任", "Closely aligned with macro cost reduction demands, providing completely transparent business travel management through algorithm-driven solutions, reshaping internal collaboration trust in large government and enterprise organizations") }, { label: B("核心能力", "Core Capability"), value: B("基於零信任架構實現數據可用不可見，精準量化多方協作貢獻，交易即秒級自動清算", "Based on zero-trust architecture ensuring data is usable but invisible, precisely quantifying multi-party collaboration contributions with instant automatic settlement") }, { label: B("目標客戶", "Target Clients"), value: B("大型國資企業、私營企業集團", "Large state-owned enterprises, private enterprise groups") }] },
      { num: "X2", title: B("空間資產智能化調度平台", "Intelligent Space Asset Scheduling Platform"), subtitle: B("多方利益實時動態清算", "Real-Time Dynamic Settlement of Multi-Party Interests"), content: B("利用 AI 智能體直接接管線下物理空間，實現無人化運營調度與多方資產持有者的秒級利潤清算，實現多方利益實時動態清算。", "Using AI agents to directly manage offline physical spaces, achieving unmanned operational scheduling and instant profit settlement for multi-party asset holders, enabling real-time dynamic settlement of multi-party interests."),
        details: [{ label: B("核心策略", "Core Strategy"), value: B("利用 AI 智能體直接接管線下物理空間，實現無人化運營調度與多方資產持有者的秒級利潤清算", "Using AI agents to directly manage offline physical spaces, achieving unmanned operational scheduling and instant profit settlement for multi-party asset holders") }, { label: B("技術亮點", "Technical Highlights"), value: B("實現多方利益實時動態清算，基於 AHA 架構打通智能體、人類運營者與物理資產的協同鏈路", "Achieving real-time dynamic settlement of multi-party interests, connecting AI agents, human operators, and physical assets through the AHA architecture") }, { label: B("應用場景", "Application Scenarios"), value: B("酒店、聯合辦公、商業地產等重資產空間的智能化運營與收益分配", "Intelligent operation and revenue distribution for heavy-asset spaces including hotels, co-working spaces, and commercial real estate") }] },
      { num: "X3", title: B("高端服務與科研成果轉化系統", "Premium Services & Research Commercialization System"), subtitle: B("連接全球頂尖學府", "Connecting World-Class Academic Institutions"), content: B("連接全球頂尖學府，在極高端的體驗經濟與科研成果轉化中，全面跑通高客單價的跨界分潤模型。", "Connecting world-class academic institutions, fully validating high-ticket cross-border profit-sharing models in premium experience economy and research commercialization."),
        details: [{ label: B("核心策略", "Core Strategy"), value: B("連接全球頂尖學府，在極高端的體驗經濟與科研成果轉化中，全面跑通高客單價的跨界分潤模型", "Connecting world-class academic institutions, fully validating high-ticket cross-border profit-sharing models in premium experience economy and research commercialization") }, { label: B("核心能力", "Core Capability"), value: B("基於 OPC Global 超級專家網絡，將頂尖學術資源與商業場景深度融合，實現知識變現與體驗升級", "Based on the OPC Global super expert network, deeply integrating top academic resources with business scenarios for knowledge monetization and experience enhancement") }, { label: B("目標人群", "Target Audience"), value: B("高淨值人群、學術機構、科研院所", "High-net-worth individuals, academic institutions, research institutes") }] },
    ],
    philosophy: { eyebrow: B("商業逻輯", "Business Logic"), title: B("將 1+1 的基礎設施能力注入高淨值、重資產場景", "Injecting 1+1 Infrastructure into High-Value, Heavy-Asset Scenarios"), content: B("每一個 AI 轉型場景都是 AHA 底層架構與 OPC Global 專家網絡交匯產生的標桿級範例，引領行業範式轉移", "Each AI transformation scenario is a benchmark exemplar generated at the intersection of the AHA architecture and OPC Global expert network, leading industry paradigm shifts"), cta: B("關於我們", "About Us") },
  },
  partners: {
    eyebrow: B("合作夥伴", "Partners"), title: B("與全球領先機構共建生態", "Building Ecosystems with Global Leaders"), viewAll: B("查看全部合作夥伴", "View All Partners"),
    aboutEyebrow: B("合作夥伴", "Strategic Partners"), aboutIntro: B("TABLE AI 與教育、科技、醫療、文化等領域的頂尖機構建立深度合作，共同推動智能經濟基礎設施的落地與發展。", "TABLE AI establishes deep partnerships with leading institutions across education, technology, healthcare, and culture to jointly advance intelligent economy infrastructure."),
    visit: B("訪問官網", "Visit Website"),
    categories: { education: B("教育", "Education"), technology: B("科技", "Technology"), medical: B("醫療", "Healthcare"), alliance: B("聯盟", "Alliance"), culture: B("文化", "Culture"), tourism: B("旅遊", "Tourism"), research: B("研究", "Research") },
    list: [
      { name: B("伯禹教育", "Boyuai Education"), url: "https://www.boyuai.com", category: "education", desc: B("伯禹教育是一家專注於人工智能（AI）教育的機構，致力於培養卓越的人工智能算法工程師和研究員。其課程體系基於上海交通大學ACM班的人工智能專業課程進行創新，涵蓋數學基礎、編程能力、機器學習、深度學習及應用實踐。", "Boyuai Education is an institution focused on artificial intelligence education, dedicated to cultivating outstanding AI algorithm engineers and researchers. Its curriculum is innovated based on the AI professional courses of Shanghai Jiao Tong University's ACM Class.") },
      { name: B("瀾碼科技", "Lanma Technology"), url: "https://www.xbotspace.com", category: "technology", desc: B("瀾碼科技是一家基於大語言模型（LLM）的企業級AI Agent（智能體）平台公司。其核心理念是「專家知識賦能基層業務單元」。核心產品AskXBOT平台能夠將大語言模型的能力抽象為文檔檢索、AI調用、數據查詢等功能。", "Lanma Technology is an enterprise-grade AI Agent platform company based on Large Language Models (LLM). Its core philosophy is 'Expert Knowledge Empowering Frontline Business Units'. The core product AskXBOT platform abstracts LLM capabilities into document retrieval, AI invocation, and data querying.") },
      { name: B("首都醫科大學附屬北京朝陽醫院", "Beijing Chaoyang Hospital, Capital Medical University"), url: "https://www.bjcyh.com.cn", category: "medical", desc: B("首都醫科大學附屬北京朝陽醫院建於1958年，是一所集醫療、教學、科研、預防為一體的三級甲等綜合醫院。醫院是北京市呼吸疾病研究所所在地，呼吸病學是國家重點學科。", "Beijing Chaoyang Hospital, affiliated with Capital Medical University, was established in 1958. It is a Grade-A tertiary comprehensive hospital integrating medical treatment, teaching, research, and prevention. The hospital houses the Beijing Institute of Respiratory Medicine.") },
      { name: B("OPC Global（一人公司全球聯盟）", "OPC Global (One Person Company Alliance)"), url: "https://opcglobal.ai", category: "alliance", desc: B("OPC Global 是一個致力於在AI時代賦能個體和微型團隊的全球聯盟。其願景是幫助個人通過AI工具和自動化工作流實現超級個體的價值閉環。平台提供從L1（操作員）到L3（泰坦）的認證體系。", "OPC Global is a worldwide alliance dedicated to empowering individuals and micro-teams in the AI era. Its vision is to help individuals achieve the value loop of super-individuals through AI tools and automated workflows, providing certification from L1 (Operator) to L3 (Titan) levels.") },
      { name: B("Nibiru 睿悅科技", "Nibiru (RealMax Technology)"), url: "https://www.inibiru.com", category: "technology", desc: B("睿悅信息（Nibiru）是全球領先的AR/VR系統、三維數字引擎及互動式內容工具供應商。公司主營業務包括為全球XR設備制造商提供Nibiru OS操作系統，以及Nibiru Studio、Nibiru Creator等。", "Nibiru (RealMax Technology) is a globally leading AR/VR system, 3D digital engine, and interactive content tool provider. Its core offerings include Nibiru OS for global XR device manufacturers, Nibiru Studio and Nibiru Creator.") },
      { name: B("世界運河城市 Canal Walk", "World Canal Cities Canal Walk"), url: "https://www.xinhuanet.com", category: "culture", desc: B("世界運河城市 Canal Walk 行動是由「世界運河城市Canal Walk行動組委會」（成立於2024年9月）發起的一項國際文化交流倡議。該行動以運河文化為紐帶，倡導「運河漫步」的生活方式，推動全球運河城市間的互聯互通。", "World Canal Cities Canal Walk is an international cultural exchange initiative launched by the Canal Walk Action Committee (established September 2024). The initiative uses canal culture as a bond, advocating the 'Canal Walk' lifestyle and promoting interconnection among global canal cities.") },
      { name: B("中智遊集團", "CIT Group (Smart Tourism)"), url: "https://www.citgroup.cn", category: "tourism", desc: B("中智遊集團是一家專注於智慧旅遊的信息化技術服務商。主要業務涵蓋旅遊目的地的智慧營銷、規劃顧問、軟件研發與建設、以及旅遊項目的投資與運營。", "CIT Group is an information technology service provider focused on smart tourism. Its core business covers intelligent marketing, planning consulting, software development, and tourism project investment and operations.") },
      { name: B("亞洲藝術療癒研究院", "Asian Institute of Art Therapy"), url: "https://www.krirk.ac.th", category: "research", desc: B("亞洲藝術療癒研究院於2024年底在泰國格樂大學正式成立。該研究院旨在深化亞洲國家在精神健康與藝術療癒領域的合作，探索獨特的「東方療癒範式」。", "The Asian Institute of Art Therapy was officially established at Krirk University, Thailand in late 2024. The institute aims to deepen cooperation among Asian countries in mental health and art therapy, exploring a unique 'Eastern Healing Paradigm'.") },
    ],
  },
  cta: { eyebrow: B("加入我們", "Join Us"), title: B("共建智能經濟的未來", "Build the Future of Intelligent Economy"), content: B("讓全球範圍內的機器智能、人類專家與實體資產實現無摩擦的高效協同", "Enabling frictionless, high-efficiency collaboration among machine intelligence, human experts, and physical assets worldwide"), label: B("了解 TABLE AI", "Discover TABLE AI") },
  about: {
    eyebrow: B("關於我們", "About Us"), title: B("關於 TABLE AI", "About TABLE AI"),
    mission: B("使命", "Mission"),
    content: B("TABLE AI 致力於構建下一代智能經濟的基礎設施。我們通過重構底層的協作協議，徹底跨越信任與體驗的鴻溝，讓全球範圍內的機器智能、人類專家與實體資產實現無摩擦的高效協同。", "TABLE AI is committed to building the infrastructure for the next-generation intelligent economy. By reconstructing the underlying collaboration protocols, we fundamentally bridge the trust and experience divide, enabling frictionless, high-efficiency collaboration among machine intelligence, human experts, and physical assets worldwide."),
    stats: [{ value: 2026, label: B("成立年份", "Founded") }, { value: 8, suffix: "+", label: B("全球節點", "Global Nodes") }, { value: 3, label: B("業務板塊", "Business Lines") }, { value: 100, suffix: "%", label: B("自動清算", "Auto Settlement") }],
    profileEyebrow: B("企業概況", "Company Profile"), profileTitle: B("TABLE AI 集團", "TABLE AI Group"),
    profile: [
      { label: B("全稱", "Full Name"), value: B("香港泰博樂科技有限公司（TABLE AI）", "TABLE AI (香港泰博樂科技有限公司)") },
      { label: B("業務", "Business"), value: B("專家 AI 工作室：專家智能體、專家數據與評分標準、專家評測集", "Expert-AI Studio: Expert Agents, Expert Data & Rubrics, Expert Evals") },
      { label: B("定位", "Positioning"), value: B("跨越智能與實體經濟邊界的全球協同基礎設施", "Global Collaborative Infrastructure Bridging Intelligence and the Real Economy") },
      { label: B("總部", "Headquarters"), value: B("中國香港", "Hong Kong, China") },
      { label: B("全球節點", "Global Nodes"), value: B("港澳、倫敦、巴塞爾、北美及國內核心城市", "Hong Kong/Macau, London, Basel, North America, and core domestic cities") },
      { label: B("核心技術", "Core Technology"), value: B("AHA（Agent-Human-Assets）混合協作底層架構、零信任合規清算系統、OPC Global 專業級協作網絡", "AHA (Agent-Human-Assets) Hybrid Collaboration Architecture, Zero-Trust Compliance Settlement System, OPC Global Professional Collaboration Network") },
      { label: B("合規框架", "Compliance"), value: B("深度契合國家信通院可信算力標準及全球多邊稅務合規要求", "Deeply aligned with CAICT trusted computing standards and global multilateral tax compliance requirements") },
    ],
    networkEyebrow: B("全球網絡", "Global Network"), networkTitle: B("全球合夥人網絡", "Global Partner Network"), nodes: B("個節點", " Nodes"),
    locations: [
      { name: B("TABLE AI 總部", "TABLE AI HQ"), city: B("香港", "Hong Kong"), region: B("大中華區", "Greater China"), lat: 22.3193, lng: 114.1694 },
      { name: B("倫敦節點", "London Node"), city: B("倫敦", "London"), region: B("歐洲", "Europe"), lat: 51.5074, lng: -0.1278 },
      { name: B("巴塞爾節點", "Basel Node"), city: B("巴塞爾", "Basel"), region: B("歐洲", "Europe"), lat: 47.5596, lng: 7.5886 },
      { name: B("北美節點", "North America Node"), city: B("紐約", "New York"), region: B("北美", "North America"), lat: 40.7128, lng: -74.006 },
      { name: B("北京節點", "Beijing Node"), city: B("北京", "Beijing"), region: B("大中華區", "Greater China"), lat: 39.9042, lng: 116.4074 },
      { name: B("上海節點", "Shanghai Node"), city: B("上海", "Shanghai"), region: B("大中華區", "Greater China"), lat: 31.2304, lng: 121.4737 },
      { name: B("深圳節點", "Shenzhen Node"), city: B("深圳", "Shenzhen"), region: B("大中華區", "Greater China"), lat: 22.5431, lng: 114.0579 },
    ],
    ctaTitle: B("加入我們，共建智能經濟的未來", "Join us in building the future of intelligent economy"), email: "hi@tableai.ai",
  },
  footer: {
    tagline: B("構築 AI 時代的全球智能協同與價值清算基礎設施", "Architecting the Global Infrastructure for AI-Era Collaboration and Value Settlement"),
    cities: B("中國香港 | 倫敦 | 巴塞爾 | 北美 | 北京 | 上海 | 深圳", "Hong Kong | London | Basel | North America | Beijing | Shanghai | Shenzhen"),
    columns: [
      { title: B("產品", "Products"), links: [{ label: B("專家 AI 工作室", "Expert-AI Studio"), href: "/studio" }, { label: B("智能協作協議", "Smart Protocol"), href: "/protocol" }, { label: B("OPC 全球網絡", "OPC Network"), href: "/network" }, { label: B("AI 實驗室", "AI Labs"), href: "/business" }] },
      { title: B("公司", "Company"), links: [{ label: B("關於我們", "About"), href: "/about" }, { label: B("合作夥伴", "Partners"), href: "/about" }, { label: B("聯繫我們", "Contact"), href: "/about" }] },
    ],
    copyright: B("© 2026 TABLE AI. 保留所有權利。", "© 2026 TABLE AI. All rights reserved."),
    privacy: B("隱私政策", "Privacy"), terms: B("服務條款", "Terms"),
  },
  common: { back: B("返回首頁", "Back to Home"), scroll: "Scroll", loading: "Loading" },
};
Object.assign(window, { SITE });
