// TABLE AI website copy — verbatim from server/seed.ts (ksamint/table-ai-website). Every string is {zh, en}.
const B = (zh, en) => ({ zh, en });
const SITE = {
  nav: [
    { href: "/protocol", label: B("协议", "Protocol") },
    { href: "/network", label: B("网络", "Network") },
    { href: "/business", label: B("AI实验室", "AI Labs") },
    { href: "/about", label: B("关于", "About") },
  ],
  hero: {
    eyebrow: B("全球协同基础设施", "Global Collaborative Infrastructure"),
    title: B("TABLE AI", "TABLE AI"),
    subtitle: B("跨越智能与实体经济边界的全球协同基础设施", "Global Collaborative Infrastructure Bridging Intelligence and the Real Economy"),
    tagline: B("跨越信任与体验的鸿沟", "Bridging the Trust and Experience Divide"),
    insight: B("在全球企业加速拥抱大模型技术的当下，TABLE AI 洞察到：AI 智能体向核心业务线渗透的最大瓶颈，已不再是算力或模型参数，而是“人与数据”的交汇摩擦。", "As global enterprises accelerate their adoption of large model technologies, TABLE AI has identified a critical insight: the greatest bottleneck for AI agents penetrating core business lines is no longer computing power or model parameters, but the friction at the intersection of people and data."),
    cta1: B("探索 AHA 架构", "Explore AHA Architecture"),
    cta2: B("了解更多", "Learn More"),
  },
  stats: [
    { value: 7, suffix: "+", label: B("全球枢纽节点", "Global Hub Nodes") },
    { value: 3, suffix: "", label: B("AI 转型场景", "AI Transformation Scenarios") },
    { value: 100, suffix: "%", label: B("秒级自动清算", "Instant Auto Settlement"), accent: true },
    { value: "AHA", suffix: "", label: B("底层协作架构", "Foundation Architecture") },
  ],
  insight: { eyebrow: B("核心洞察与企业使命", "Our Vision & Mission") },
  thresholds: [
    { label: B("临界点 01", "Threshold 01"), title: B("信任临界点", "Trust Threshold"), desc: B("缺乏零信任的数据流转与财务清算机制，企业不敢开放核心场景，多方协作的利益分配无法达成共识。", "Without zero-trust data circulation and financial settlement mechanisms, enterprises dare not open core scenarios, and consensus on multi-party interest distribution remains elusive.") },
    { label: B("临界点 02", "Threshold 02"), title: B("体验临界点", "Experience Threshold"), desc: B("在极高复杂度和零容错率的商业博弈中，纯粹的算法存在物理盲区，无法独立交付具备专业深度与责任兜底的极致体验。", "In high-complexity, zero-tolerance business dynamics, pure algorithms have physical blind spots and cannot independently deliver the ultimate experience with professional depth and accountability.") },
  ],
  aha: {
    eyebrow: B("底层协作架构：AHA 体系", "The AHA Architecture"),
    title: B("AHA 体系", "The AHA Architecture"),
    subtitle: B("Agent-Human-Assets 智能体-人-资产 混合协作底层架构", "Agent-Human-Assets Hybrid Collaboration Architecture"),
    content: B("为解决产业痛点，TABLE AI 自主研发了 AHA（Agent-Human-Assets，智能体-人-资产）混合协作底层架构。作为智能经济的“协议层”，AHA 架构原生打通了机器算力、人类智力与物理资产的交互链路。它将复杂的现实商业系统转化为可计算、可追溯、绝对可信的代码逻辑，为 AI 在真实世界的大规模部署提供了不可或缺的技术基石。", "To solve industry pain points, TABLE AI has independently developed the AHA (Agent-Human-Assets) hybrid collaboration architecture. As the 'protocol layer' of the intelligent economy, the AHA architecture natively connects the interaction chains of machine computing power, human intelligence, and physical assets. It transforms complex real-world business systems into computable, traceable, and absolutely trustworthy code logic, providing an indispensable technological cornerstone for the large-scale deployment of AI in the real world."),
    items: [
      { letter: "A", label: B("Agent 智能体", "Agent"), desc: B("机器算力", "Machine Computing"), desc2: B("机器算力与自动化执行", "Machine computing power and automated execution"), detail: B("将复杂的现实商业系统转化为可计算、可追溯的代码逻辑", "Transforming complex real-world business systems into computable, traceable code logic") },
      { letter: "H", label: B("Human 人", "Human"), desc: B("人类智力", "Human Intelligence"), desc2: B("人类智力与专业背书", "Human intelligence and professional endorsement"), detail: B("保留人类不可替代的专业背书与极限纠偏能力", "Preserving irreplaceable human professional endorsement and ultimate error-correction capabilities") },
      { letter: "A", label: B("Assets 资产", "Assets"), desc: B("物理资产", "Physical Assets"), desc2: B("物理资产与实体经济", "Physical assets and real economy"), detail: B("原生打通机器算力、人类智力与物理资产的交互链路", "Natively connecting the interaction chains of machine computing, human intelligence, and physical assets") },
    ],
    visualEyebrow: B("底层架构", "Foundation Architecture"),
    visualTitle: B("AHA 体系 —— 智能体-人-资产", "AHA Architecture — Agent-Human-Assets"),
  },
  business: {
    eyebrow: B("商业部署矩阵", "Business Deployment Matrix"),
    title: "1+1+X",
    subtitle: B("战略飞轮", "Strategic Flywheel"),
    content: B("基于 AHA 底层架构，TABLE AI 构建了极具延展性的“1+1+X”商业落地矩阵。这不仅是一套技术部署方案，更是系统性破解行业痛点的结构化解法。", "Built upon the AHA architecture, TABLE AI has constructed a highly extensible '1+1+X' business deployment matrix. This is not merely a technology deployment plan, but a structured solution for systematically solving industry pain points."),
    learnMore: B("深入了解", "Learn More"),
  },
  protocol: {
    num: "01", pillar: B("跨越信任临界点", "Crossing the Trust Threshold"),
    title: B("第一个「1」：跨越“信任”临界点", "The First '1': Crossing the Trust Threshold"),
    subtitle: B("一套零信任、自迭代的合规清算系统", "A Zero-Trust, Self-Iterating Compliance Settlement System"),
    content: B("基于“零信任（Zero-Trust）”架构打造的企业级智能协同与全球分账系统。它在确保数据“可用不可见”的前提下，精准量化多方协作贡献，实现交易即秒级自动清算。系统内置自迭代机制，深度契合国家信通院可信算力标准及全球多边税务合规要求，用系统级的确定性彻底消除跨组织协作的摩擦成本。", "An enterprise-grade intelligent collaboration and global settlement system built on Zero-Trust architecture. While ensuring data remains 'usable but invisible,' it precisely quantifies multi-party collaboration contributions and achieves instant automatic settlement at the moment of transaction. With built-in self-iterating mechanisms, the system deeply aligns with CAICT trusted computing standards and global multilateral tax compliance requirements, using system-level certainty to completely eliminate the friction costs of cross-organizational collaboration."),
    overview: B("协议概述", "Protocol Overview"),
    mechanismsEyebrow: B("核心机制", "Core Mechanisms"), mechanismsTitle: B("零信任清算系统如何运转", "How the Zero-Trust Settlement System Works"),
    features: [
      { title: B("零信任数据流转", "Zero-Trust Data Circulation"), content: B("确保数据“可用不可见”，在保护商业机密的前提下实现多方协作的精准贡献量化与利益分配。", "Ensures data remains 'usable but invisible,' enabling precise contribution quantification and interest distribution in multi-party collaboration while protecting commercial secrets.") },
      { title: B("秒级自动清算", "Instant Automatic Settlement"), content: B("交易达成的瞬间，系统触发零摩擦、零争议的秒级自动清算，彻底消除跨组织协作的结算延迟。", "The moment a transaction is completed, the system triggers zero-friction, zero-dispute instant automatic settlement, completely eliminating settlement delays in cross-organizational collaboration.") },
      { title: B("全球合规自迭代", "Global Compliance Self-Iteration"), content: B("系统内置自迭代机制，深度契合国家信通院可信算力标准及全球多边税务合规要求，确保绝对合规。", "Built-in self-iterating mechanisms deeply align with CAICT trusted computing standards and global multilateral tax compliance requirements, ensuring absolute compliance.") },
    ],
    highlightsEyebrow: B("技术亮点", "Technical Highlights"),
    highlights: [
      { title: B("零信任架构", "Zero-Trust Architecture"), desc: B("确保数据可用不可见，在保护商业机密的前提下实现多方协作的精准贡献量化", "Ensures data remains usable but invisible, enabling precise contribution quantification in multi-party collaboration while protecting commercial secrets") },
      { title: B("秒级自动清算", "Instant Automatic Settlement"), desc: B("交易达成的瞬间触发零摩擦、零争议的秒级自动清算，彻底消除结算延迟", "Instant zero-friction, zero-dispute automatic settlement triggered at the moment of transaction, completely eliminating settlement delays") },
      { title: B("可信算力标准", "Trusted Computing Standards"), desc: B("深度契合国家信通院可信算力标准，确保计算过程透明可审计", "Deeply aligned with CAICT trusted computing standards, ensuring transparent and auditable computation processes") },
      { title: B("全球多边合规", "Global Multilateral Compliance"), desc: B("系统内置自迭代机制，深度契合全球多边税务合规要求，用系统级确定性消除摩擦成本", "Built-in self-iterating mechanisms aligned with global multilateral tax compliance requirements, using system-level certainty to eliminate friction costs") },
    ],
    ctaTitle: B("探索 OPC Global 专业级协作网络", "Explore the OPC Global Professional Network"), ctaLabel: B("了解网络", "Discover the Network"),
  },
  network: {
    num: "02", pillar: B("跨越体验临界点", "Crossing the Experience Threshold"),
    title: B("第二个「1」：跨越“体验”临界点", "The Second '1': Crossing the Experience Threshold"),
    subtitle: B("OPC Global — 全球化专业级协作网络", "OPC Global — A Global Professional Collaboration Network"),
    content: B("单纯的代码无法独立应对真实商业的复杂性，高风险场景依然需要人在回路以明确权责、控制风险。依托遍布伦敦、巴塞尔、北美及大中华区核心枢纽的算力与人才节点，我们构建了基于“人在回路 (Human-in-the-loop)”理念的 OPC Global 超级专家网络。我们将顶尖专家的隐性经验转化为 AI 模型，同时保留人类不可替代的专业背书与极限纠偏能力，为 AI 的真实商业交付提供最高标准的体验兜底。", "Code alone cannot independently handle the complexity of real-world business. High-risk scenarios still require humans in the loop to clarify responsibilities and control risks. Leveraging computing power and talent nodes across core hubs in London, Basel, North America, and Greater China, we have built the OPC Global super expert network based on the 'Human-in-the-loop' philosophy. We transform the tacit experience of top experts into AI models while preserving the irreplaceable human professional endorsement and ultimate error-correction capabilities, providing the highest standard of experience assurance for AI's real-world business delivery."),
    overview: B("网络概述", "Network Overview"),
    pillarsEyebrow: B("核心支柱", "Core Pillars"), pillarsTitle: B("OPC Global 网络架构", "OPC Global Network Architecture"),
    features: [
      { title: B("人在回路 (Human-in-the-loop)", "Human-in-the-Loop"), content: B("高风险场景依然需要人在回路以明确权责、控制风险，保留人类不可替代的专业背书与极限纠偏能力。", "High-risk scenarios still require humans in the loop to clarify responsibilities and control risks, preserving the irreplaceable human professional endorsement and ultimate error-correction capabilities.") },
      { title: B("隐性经验 AI 化", "Tacit Experience to AI"), content: B("将遍布顶尖高校、医疗机构及商业领域的专家隐性经验转化为可规模化的 AI 专家模型。", "Transforming tacit expert experience across top universities, medical institutions, and business domains into scalable AI expert models.") },
      { title: B("全球枢纽网络", "Global Hub Network"), content: B("依托遍布伦敦、巴塞尔、北美及大中华区核心枢纽的算力与人才节点，构建全球化专业级协作网络。", "Leveraging computing power and talent nodes across core hubs in London, Basel, North America, and Greater China to build a global professional collaboration network.") },
    ],
    hubsEyebrow: B("全球布局", "Global Presence"), hubsTitle: B("枢纽城市网络", "Hub City Network"),
    hubs: [
      { city: B("中国香港", "Hong Kong"), region: B("大中华区", "Greater China") }, { city: B("伦敦", "London"), region: B("欧洲", "Europe") }, { city: B("巴塞尔", "Basel"), region: B("欧洲", "Europe") }, { city: B("北美", "North America"), region: B("美洲", "Americas") },
      { city: B("北京", "Beijing"), region: B("大中华区", "Greater China") }, { city: B("上海", "Shanghai"), region: B("大中华区", "Greater China") }, { city: B("深圳", "Shenzhen"), region: B("大中华区", "Greater China") }, { city: B("澳门", "Macau"), region: B("大中华区", "Greater China") },
    ],
    metrics: [
      { icon: "users", num: B("Human-in-the-Loop", "Human-in-the-Loop"), label: B("人在回路", "Human-in-the-Loop"), desc: B("高风险场景依然需要人在回路以明确权责、控制风险，保留人类不可替代的专业背书与极限纠偏能力", "High-risk scenarios still require humans in the loop to clarify responsibilities and control risks, preserving irreplaceable human professional endorsement and ultimate error-correction capabilities") },
      { icon: "cpu", num: B("AI + Expert", "AI + Expert"), label: B("隐性经验 AI 化", "Tacit Experience to AI"), desc: B("将顶尖专家的隐性经验转化为 AI 模型，实现专业知识的规模化复制与持续进化", "Transforming tacit experience of top experts into AI models, enabling scalable replication and continuous evolution of professional knowledge") },
      { icon: "zap", num: B("最高标准", "Highest Standard"), label: B("体验兜底", "Experience Assurance"), desc: B("为 AI 的真实商业交付提供最高标准的体验兜底，确保专业深度与责任担当", "Providing the highest standard of experience assurance for AI's real-world business delivery, ensuring professional depth and accountability") },
    ],
    ctaTitle: B("探索 AI 实验室", "Explore AI Labs"), ctaLabel: B("了解实验室", "Discover AI Labs"),
  },
  labs: {
    num: "03", pillar: B("引领范式转移", "Leading Paradigm Shift"),
    title: B("乘数「X」：引领范式转移", "The Multiplier 'X': Leading Paradigm Shift"),
    subtitle: B("X 个具备行业领先范例的 AI 转型场景", "X Industry-Leading AI Transformation Scenarios"),
    content: B("TABLE AI 正将 1+1 的基础设施能力，注入亟待 AI 转型的高净值、重资产场景，打造标杆级范例。", "TABLE AI is injecting its 1+1 infrastructure capabilities into high-value, heavy-asset scenarios urgently awaiting AI transformation, creating benchmark-level exemplars."),
    overview: B("实验室概述", "Labs Overview"),
    homeEyebrow: B("乘数「X」", "Multiplier X"), homeTitle: B("X 个 AI 转型场景", "X AI Transformation Scenarios"), viewAll: B("查看全部", "View All"), details: B("了解详情", "Details"),
    items: [
      { num: "X1", title: B("合规商旅与供应链管家", "Compliant Business Travel & Supply Chain Steward"), subtitle: B("重塑大型政企内部协作信任", "Reshaping Internal Collaboration Trust in Large Government and Enterprise Organizations"), content: B("紧贴宏观“降本增效”刚需，通过算法驱动，为大型国资与私企提供彻底透明、消除一切灰色地带的差旅管家系统，重塑大型政企内部协作信任。", "Closely aligned with the macro demand for cost reduction and efficiency improvement, providing large state-owned and private enterprises with completely transparent business travel management systems through algorithm-driven solutions, eliminating all gray areas and reshaping internal collaboration trust."),
        details: [{ label: B("核心策略", "Core Strategy"), value: B("紧贴宏观降本增效刚需，通过算法驱动，为大型国资与私企提供彻底透明、消除一切灰色地带的差旅管家系统，重塑大型政企内部协作信任", "Closely aligned with macro cost reduction demands, providing completely transparent business travel management through algorithm-driven solutions, reshaping internal collaboration trust in large government and enterprise organizations") }, { label: B("核心能力", "Core Capability"), value: B("基于零信任架构实现数据可用不可见，精准量化多方协作贡献，交易即秒级自动清算", "Based on zero-trust architecture ensuring data is usable but invisible, precisely quantifying multi-party collaboration contributions with instant automatic settlement") }, { label: B("目标客户", "Target Clients"), value: B("大型国资企业、私营企业集团", "Large state-owned enterprises, private enterprise groups") }] },
      { num: "X2", title: B("空间资产智能化调度平台", "Intelligent Space Asset Scheduling Platform"), subtitle: B("多方利益实时动态清算", "Real-Time Dynamic Settlement of Multi-Party Interests"), content: B("利用 AI 智能体直接接管线下物理空间，实现无人化运营调度与多方资产持有者的秒级利润清算，实现多方利益实时动态清算。", "Using AI agents to directly manage offline physical spaces, achieving unmanned operational scheduling and instant profit settlement for multi-party asset holders, enabling real-time dynamic settlement of multi-party interests."),
        details: [{ label: B("核心策略", "Core Strategy"), value: B("利用 AI 智能体直接接管线下物理空间，实现无人化运营调度与多方资产持有者的秒级利润清算", "Using AI agents to directly manage offline physical spaces, achieving unmanned operational scheduling and instant profit settlement for multi-party asset holders") }, { label: B("技术亮点", "Technical Highlights"), value: B("实现多方利益实时动态清算，基于 AHA 架构打通智能体、人类运营者与物理资产的协同链路", "Achieving real-time dynamic settlement of multi-party interests, connecting AI agents, human operators, and physical assets through the AHA architecture") }, { label: B("应用场景", "Application Scenarios"), value: B("酒店、联合办公、商业地产等重资产空间的智能化运营与收益分配", "Intelligent operation and revenue distribution for heavy-asset spaces including hotels, co-working spaces, and commercial real estate") }] },
      { num: "X3", title: B("高端服务与科研成果转化系统", "Premium Services & Research Commercialization System"), subtitle: B("连接全球顶尖学府", "Connecting World-Class Academic Institutions"), content: B("连接全球顶尖学府，在极高端的体验经济与科研成果转化中，全面跑通高客单价的跨界分润模型。", "Connecting world-class academic institutions, fully validating high-ticket cross-border profit-sharing models in premium experience economy and research commercialization."),
        details: [{ label: B("核心策略", "Core Strategy"), value: B("连接全球顶尖学府，在极高端的体验经济与科研成果转化中，全面跑通高客单价的跨界分润模型", "Connecting world-class academic institutions, fully validating high-ticket cross-border profit-sharing models in premium experience economy and research commercialization") }, { label: B("核心能力", "Core Capability"), value: B("基于 OPC Global 超级专家网络，将顶尖学术资源与商业场景深度融合，实现知识变现与体验升级", "Based on the OPC Global super expert network, deeply integrating top academic resources with business scenarios for knowledge monetization and experience enhancement") }, { label: B("目标人群", "Target Audience"), value: B("高净值人群、学术机构、科研院所", "High-net-worth individuals, academic institutions, research institutes") }] },
    ],
    philosophy: { eyebrow: B("商业逻辑", "Business Logic"), title: B("将 1+1 的基础设施能力注入高净值、重资产场景", "Injecting 1+1 Infrastructure into High-Value, Heavy-Asset Scenarios"), content: B("每一个 AI 转型场景都是 AHA 底层架构与 OPC Global 专家网络交汇产生的标杆级范例，引领行业范式转移", "Each AI transformation scenario is a benchmark exemplar generated at the intersection of the AHA architecture and OPC Global expert network, leading industry paradigm shifts"), cta: B("关于我们", "About Us") },
  },
  partners: {
    eyebrow: B("合作伙伴", "Partners"), title: B("与全球领先机构共建生态", "Building Ecosystems with Global Leaders"), viewAll: B("查看全部合作伙伴", "View All Partners"),
    aboutEyebrow: B("合作伙伴", "Strategic Partners"), aboutIntro: B("TABLE AI 与教育、科技、医疗、文化等领域的顶尖机构建立深度合作，共同推动智能经济基础设施的落地与发展。", "TABLE AI establishes deep partnerships with leading institutions across education, technology, healthcare, and culture to jointly advance intelligent economy infrastructure."),
    visit: B("访问官网", "Visit Website"),
    categories: { education: B("教育", "Education"), technology: B("科技", "Technology"), medical: B("医疗", "Healthcare"), alliance: B("联盟", "Alliance"), culture: B("文化", "Culture"), tourism: B("旅游", "Tourism"), research: B("研究", "Research") },
    list: [
      { name: B("伯禹教育", "Boyuai Education"), url: "https://www.boyuai.com", category: "education", desc: B("伯禹教育是一家专注于人工智能（AI）教育的机构，致力于培养卓越的人工智能算法工程师和研究员。其课程体系基于上海交通大学ACM班的人工智能专业课程进行创新，涵盖数学基础、编程能力、机器学习、深度学习及应用实践。", "Boyuai Education is an institution focused on artificial intelligence education, dedicated to cultivating outstanding AI algorithm engineers and researchers. Its curriculum is innovated based on the AI professional courses of Shanghai Jiao Tong University's ACM Class.") },
      { name: B("澜码科技", "Lanma Technology"), url: "https://www.xbotspace.com", category: "technology", desc: B("澜码科技是一家基于大语言模型（LLM）的企业级AI Agent（智能体）平台公司。其核心理念是「专家知识赋能基层业务单元」。核心产品AskXBOT平台能够将大语言模型的能力抽象为文档检索、AI调用、数据查询等功能。", "Lanma Technology is an enterprise-grade AI Agent platform company based on Large Language Models (LLM). Its core philosophy is 'Expert Knowledge Empowering Frontline Business Units'. The core product AskXBOT platform abstracts LLM capabilities into document retrieval, AI invocation, and data querying.") },
      { name: B("首都医科大学附属北京朝阳医院", "Beijing Chaoyang Hospital, Capital Medical University"), url: "https://www.bjcyh.com.cn", category: "medical", desc: B("首都医科大学附属北京朝阳医院建于1958年，是一所集医疗、教学、科研、预防为一体的三级甲等综合医院。医院是北京市呼吸疾病研究所所在地，呼吸病学是国家重点学科。", "Beijing Chaoyang Hospital, affiliated with Capital Medical University, was established in 1958. It is a Grade-A tertiary comprehensive hospital integrating medical treatment, teaching, research, and prevention. The hospital houses the Beijing Institute of Respiratory Medicine.") },
      { name: B("OPC Global（一人公司全球联盟）", "OPC Global (One Person Company Alliance)"), url: "https://opcglobal.ai", category: "alliance", desc: B("OPC Global 是一个致力于在AI时代赋能个体和微型团队的全球联盟。其愿景是帮助个人通过AI工具和自动化工作流实现超级个体的价值闭环。平台提供从L1（操作员）到L3（泰坦）的认证体系。", "OPC Global is a worldwide alliance dedicated to empowering individuals and micro-teams in the AI era. Its vision is to help individuals achieve the value loop of super-individuals through AI tools and automated workflows, providing certification from L1 (Operator) to L3 (Titan) levels.") },
      { name: B("Nibiru 睿悦科技", "Nibiru (RealMax Technology)"), url: "https://www.inibiru.com", category: "technology", desc: B("睿悦信息（Nibiru）是全球领先的AR/VR系统、三维数字引擎及互动式内容工具供应商。公司主营业务包括为全球XR设备制造商提供Nibiru OS操作系统，以及Nibiru Studio、Nibiru Creator等。", "Nibiru (RealMax Technology) is a globally leading AR/VR system, 3D digital engine, and interactive content tool provider. Its core offerings include Nibiru OS for global XR device manufacturers, Nibiru Studio and Nibiru Creator.") },
      { name: B("世界运河城市 Canal Walk", "World Canal Cities Canal Walk"), url: "https://www.xinhuanet.com", category: "culture", desc: B("世界运河城市 Canal Walk 行动是由「世界运河城市Canal Walk行动组委会」（成立于2024年9月）发起的一项国际文化交流倡议。该行动以运河文化为纽带，倡导「运河漫步」的生活方式，推动全球运河城市间的互联互通。", "World Canal Cities Canal Walk is an international cultural exchange initiative launched by the Canal Walk Action Committee (established September 2024). The initiative uses canal culture as a bond, advocating the 'Canal Walk' lifestyle and promoting interconnection among global canal cities.") },
      { name: B("中智游集团", "CIT Group (Smart Tourism)"), url: "https://www.citgroup.cn", category: "tourism", desc: B("中智游集团是一家专注于智慧旅游的信息化技术服务商。主要业务涵盖旅游目的地的智慧营销、规划顾问、软件研发与建设、以及旅游项目的投资与运营。", "CIT Group is an information technology service provider focused on smart tourism. Its core business covers intelligent marketing, planning consulting, software development, and tourism project investment and operations.") },
      { name: B("亚洲艺术疗愈研究院", "Asian Institute of Art Therapy"), url: "https://www.krirk.ac.th", category: "research", desc: B("亚洲艺术疗愈研究院于2024年底在泰国格乐大学正式成立。该研究院旨在深化亚洲国家在精神健康与艺术疗愈领域的合作，探索独特的「东方疗愈范式」。", "The Asian Institute of Art Therapy was officially established at Krirk University, Thailand in late 2024. The institute aims to deepen cooperation among Asian countries in mental health and art therapy, exploring a unique 'Eastern Healing Paradigm'.") },
    ],
  },
  cta: { eyebrow: B("加入我们", "Join Us"), title: B("共建智能经济的未来", "Build the Future of Intelligent Economy"), content: B("让全球范围内的机器智能、人类专家与实体资产实现无摩擦的高效协同", "Enabling frictionless, high-efficiency collaboration among machine intelligence, human experts, and physical assets worldwide"), label: B("了解 TABLE AI", "Discover TABLE AI") },
  about: {
    eyebrow: B("关于我们", "About Us"), title: B("关于 TABLE AI", "About TABLE AI"),
    mission: B("使命", "Mission"),
    content: B("TABLE AI 致力于构建下一代智能经济的基础设施。我们通过重构底层的协作协议，彻底跨越信任与体验的鸿沟，让全球范围内的机器智能、人类专家与实体资产实现无摩擦的高效协同。", "TABLE AI is committed to building the infrastructure for the next-generation intelligent economy. By reconstructing the underlying collaboration protocols, we fundamentally bridge the trust and experience divide, enabling frictionless, high-efficiency collaboration among machine intelligence, human experts, and physical assets worldwide."),
    stats: [{ value: 2026, label: B("成立年份", "Founded") }, { value: 8, suffix: "+", label: B("全球节点", "Global Nodes") }, { value: 3, label: B("业务板块", "Business Lines") }, { value: 100, suffix: "%", label: B("自动清算", "Auto Settlement") }],
    profileEyebrow: B("企业概况", "Company Profile"), profileTitle: B("TABLE AI 集团", "TABLE AI Group"),
    profile: [
      { label: B("全称", "Full Name"), value: B("TABLE AI", "TABLE AI") },
      { label: B("定位", "Positioning"), value: B("跨越智能与实体经济边界的全球协同基础设施", "Global Collaborative Infrastructure Bridging Intelligence and the Real Economy") },
      { label: B("总部", "Headquarters"), value: B("中国香港", "Hong Kong, China") },
      { label: B("全球节点", "Global Nodes"), value: B("港澳、伦敦、巴塞尔、北美及国内核心城市", "Hong Kong/Macau, London, Basel, North America, and core domestic cities") },
      { label: B("核心技术", "Core Technology"), value: B("AHA（Agent-Human-Assets）混合协作底层架构、零信任合规清算系统、OPC Global 专业级协作网络", "AHA (Agent-Human-Assets) Hybrid Collaboration Architecture, Zero-Trust Compliance Settlement System, OPC Global Professional Collaboration Network") },
      { label: B("合规框架", "Compliance"), value: B("深度契合国家信通院可信算力标准及全球多边税务合规要求", "Deeply aligned with CAICT trusted computing standards and global multilateral tax compliance requirements") },
    ],
    networkEyebrow: B("全球网络", "Global Network"), networkTitle: B("全球合伙人网络", "Global Partner Network"), nodes: B("个节点", " Nodes"),
    locations: [
      { name: B("TABLE AI 总部", "TABLE AI HQ"), city: B("香港", "Hong Kong"), region: B("大中华区", "Greater China"), lat: 22.3193, lng: 114.1694 },
      { name: B("伦敦节点", "London Node"), city: B("伦敦", "London"), region: B("欧洲", "Europe"), lat: 51.5074, lng: -0.1278 },
      { name: B("巴塞尔节点", "Basel Node"), city: B("巴塞尔", "Basel"), region: B("欧洲", "Europe"), lat: 47.5596, lng: 7.5886 },
      { name: B("北美节点", "North America Node"), city: B("纽约", "New York"), region: B("北美", "North America"), lat: 40.7128, lng: -74.006 },
      { name: B("北京节点", "Beijing Node"), city: B("北京", "Beijing"), region: B("大中华区", "Greater China"), lat: 39.9042, lng: 116.4074 },
      { name: B("上海节点", "Shanghai Node"), city: B("上海", "Shanghai"), region: B("大中华区", "Greater China"), lat: 31.2304, lng: 121.4737 },
      { name: B("深圳节点", "Shenzhen Node"), city: B("深圳", "Shenzhen"), region: B("大中华区", "Greater China"), lat: 22.5431, lng: 114.0579 },
    ],
    ctaTitle: B("加入我们，共建智能经济的未来", "Join us in building the future of intelligent economy"), email: "hi@tableai.ai",
  },
  footer: {
    tagline: B("构筑 AI 时代的全球智能协同与价值清算基础设施", "Architecting the Global Infrastructure for AI-Era Collaboration and Value Settlement"),
    cities: B("中国香港 | 伦敦 | 巴塞尔 | 北美 | 北京 | 上海 | 深圳", "Hong Kong | London | Basel | North America | Beijing | Shanghai | Shenzhen"),
    columns: [
      { title: B("产品", "Products"), links: [{ label: B("智能协作协议", "Smart Protocol"), href: "/protocol" }, { label: B("OPC 全球网络", "OPC Network"), href: "/network" }, { label: B("AI 实验室", "AI Labs"), href: "/business" }] },
      { title: B("公司", "Company"), links: [{ label: B("关于我们", "About"), href: "/about" }, { label: B("合作伙伴", "Partners"), href: "/about" }, { label: B("联系我们", "Contact"), href: "/about" }] },
    ],
    copyright: B("© 2026 TABLE AI. 保留所有权利。", "© 2026 TABLE AI. All rights reserved."),
    privacy: B("隐私政策", "Privacy"), terms: B("服务条款", "Terms"),
  },
  common: { back: B("返回首页", "Back to Home"), scroll: "Scroll", loading: "Loading" },
};
Object.assign(window, { SITE });
